spring:
  application:
    name: email-sender
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/email_history_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${db_username}
    password: ${db_password}
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
  mail:
    sendEmails: true
    host: smtp.gmail.com
    port: 587
    username: ${mail}
    password: ${password}
    properties:
      mail:
        smtp:
          outh: true
          starttls:
            enable: true

history:
  retention:
    period: P365D

server:
  port: 8081